export const neuroData = {
  id: 'neuro',
  imgStart: true,
  lightBg: false,
  lightText: true,
  darkText: false,
  topLine: 'Tehnică revoluționară',
  headline: 'Neurofeedback IFL',
  description:
    'Înainte de începerea terapiei propriu-zise are loc o evaluare psihologică detaliată a clientului apoi este stabilit protocolul personalizat care va fi urmat. Ședințele de neurofeedback asigură claritate, liniște și echilibru, aspecte foarte importante pentru reușita procesului terapeutic.',
  buttonLabel: 'Descoperă Neurofeedback-ul',
  fullButton: false,
  bigButton: false,
  bigFont: false,
  buttonLink: '/ce-este-neurofeedback-ul',
  img: '/images/NILF_Logo_2_W.png',
  alt: 'programmer at desk',
  dataAosTxt: 'fade-left',
  dataAosImg: 'fade-right',
  dataAosDuration: '1000',
  dataAosEasing: 'ease-in-out',
  dataAosDelay: '100',
};
export const serviciiData = {
  id: 'servicii',
  lightBg: false,
  lightText: true,
  darkText: false,
  headline: 'O metodă extrem de eficientă de optimizare a funcţiei creierului',
  topLine: 'Neurofeedback',
};
export const contactData = {
  id: 'contact',
  imgStart: false,
  lightBg: false,
  lightText: true,
  darkText: false,
  topLine: 'Vrei o consultație?',
  headline: 'Contactează-ne',
  description:
    'Contactea-ză unul din cabinetele noastre, pentru a stabili o consultație sau pentru a va lămuri în legatură cu tehnologia de Neurofeedback ILF.',
  buttonLabel: 'Contactează-ne',
  fullButton: false,
  bigButton: false,
  bigFont: false,
  buttonLink: '/contact',
  img: '/images/s2.svg',
  alt: 'programmer at desk',
  dataAosTxt: 'fade-right',
  dataAosImg: 'fade-left',
  dataAosDuration: '1000',
  dataAosEasing: 'ease-in-out',
  dataAosDelay: '100',
};
