export const neuroData = {
  id: 'neuro',
  imgStart: true,
  lightBg: true,
  lightText: false,
  darkText: true,
  topLine: 'Tehnică revoluționară',
  headline: 'Neurofeedback IFL',
  description:
    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi incidunt eum impedit illo dolorem quo dolore! Nulla sequi est exercitationem quis nostrum similique quidem, odit harum neque consequuntur perspiciatis dignissimos? ',
  buttonLabel: 'Descoperă Neurofeedback-ul',
  fullButton: false,
  bigButton: false,
  bigFont: false,
  buttonLink: '/ce-este-neurofeedback-ul',
  img: '/images/svg1.svg',
  alt: 'programmer at desk',
  dataAosTxt: 'fade-left',
  dataAosImg: 'fade-right',
  dataAosDuration: '1000',
  dataAosEasing: 'ease-in-out',
  dataAosDelay: '100',
};
export const serviciiData = {
  id: 'servicii',
  lightBg: false,
  lightText: true,
  darkText: false,
  headline: 'O metodă extrem de eficientă de optimizare a funcţiei creierului',
  topLine: 'Neurofeedback',
};
export const contactData = {
  id: 'contact',
  imgStart: false,
  lightBg: true,
  lightText: false,
  darkText: true,
  topLine: 'Vrei o consultație?',
  headline: 'Contactează-ne',
  description:
    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi incidunt eum impedit illo dolorem quo dolore! Nulla sequi est exercitationem quis nostrum similique quidem, odit harum neque consequuntur perspiciatis dignissimos? ',
  buttonLabel: 'Contacteaza-ne',
  fullButton: false,
  bigButton: false,
  bigFont: false,
  buttonLink: '/contact',
  img: '/images/svg4.svg',
  alt: 'programmer at desk',
  dataAosTxt: 'fade-right',
  dataAosImg: 'fade-left',
  dataAosDuration: '1000',
  dataAosEasing: 'ease-in-out',
  dataAosDelay: '100',
};
